[package]
name = "glr"
version = "0.1.0"
build = "build.rs"
authors = ["king1600"]

[profile.dev]
codegen-units = 8
incremental = true
overflow-checks = false

[build-dependencies]
peg = { version = "0.5" }