[workspace]
members = ["glr", "glrc"]

[profile.dev]
panic = "abort"
codegen-units = 8
incremental = true
overflow-checks = false

[profile.release]
lto = true
opt-level = 3
debug = false
panic = "abort"
overflow-checks = false
debug-assertions = false