[workspace]
members = [
    "glr",
    "glrc", 
    "glrspec"
]

[profile.dev]
codegen-units = 8
incremental = true
overflow-checks = false

[profile.release]
lto = true
debug = false
panic = "abort"
overflow-checks = false