[package]
name = "glr"
edition = "2018"
version = "0.1.0"
authors = ["king1600"]

[dependencies]
libc = { version = "0.2", default-features = false }

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["winnt", "memoryapi", "handleapi"]
